services:
  - type: cron
    name: notifier
    region: frankfurt
    plan: starter

    schedule: "*/30 * * * *"

    runtime: image
    image:
      url: docker.io/thesan/pioneer-backend:prod

    # Define env on this cron service to make sure it builds first so it won't execute before the migration is ready
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: db
          property: connectionString

      - key: QUERY_NODE_ENDPOINT
        value: https://query.joystream.org/graphql

      - key: PIONEER_URL
        value: https://pioneerapp.xyz

      - key: EMAIL_SENDER
        sync: false

      - key: SENDGRID_API_KEY
        sync: false

      - key: STARTING_BLOCK
        sync: false

      - key: APP_LOG_LEVEL
        value: verbose

  - type: web
    name: api
    region: frankfurt
    plan: free

    runtime: image
    image:
      url: docker.io/thesan/pioneer-backend:prod

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: db
          property: connectionString

      - key: QUERY_NODE_ENDPOINT
        fromService:
          type: cron
          name: notifier
          envVarKey: QUERY_NODE_ENDPOINT

      - key: PIONEER_URL
        fromService:
          type: cron
          name: notifier
          envVarKey: PIONEER_URL

      - key: EMAIL_SENDER
        fromService:
          type: cron
          name: notifier
          envVarKey: EMAIL_SENDER

      - key: SENDGRID_API_KEY
        fromService:
          type: cron
          name: notifier
          envVarKey: SENDGRID_API_KEY

      - key: APP_SECRET_KEY
        generateValue: true

databases:
  - name: db
    region: frankfurt
    plan: free
