blank_issues_enabled: true
contact_links:
  - name: "⏩ Pioneer 1.0"
    about: Please report issues regarding Pionner 1.0 (https://testnet.joystream.org/#/forum) in the main Joystream repository.
    url: https://github.com/Joystream/joystream
