name: Publish GH pages

on:
  push:
    branches:
      - deploy-project-to-gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install and Build
        run: |
          yarn install --frozen-lockfile
          yarn build
        env:
          PUBLIC_URL: https://joystream.github.io/pioneer/

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: packages/ui/build
          CLEAN: true
